### ISSUE TITLE
Currently we only support one single channel in nephos_config.yaml 

### ISSUE THREAD

**Issue by alexvicegrab** [hyperledger-labs/nephos#46]
Ideally we need to support multiple channels. Currently our `nephos_config.yaml` has only support for 1 channel, to which all peers are joined.

Instead, we should add a section in the config for channels, and reference these in the peer section by name.

We can start by separating the channel into its own section, even if we don't immediately support multiple channels, and then add the extra support, as this will require changes in several places, including:
- the configuration file itself
- the Helm Charts for the Peers
- the Nephos code that deals with creating channels
- the Nephos code that deals with joining peers to channels

**Comment by inzamam-iqbal** [comment]
@alexvicegrab @nicolapaoli The PR #90 is made such that we can bring multi org support with very few changes to nephos code. I can think of two ways to achieve it

1. Changing Helm chart. The peer helm chart expects a a secret named `channel`. We can modify it such that we give an array of secret keys under channel key. for each of them a secret will be created and will be mounted in /hl_config/channel/{secret_name}
an example value file
```yaml
......
secrets:
  ..........
  channels:
    -foochannel
    -barchannel
````
In this case after merging #90 we have to do very little change to nephos code.

2. Keep helm file as it is. Modify the config file such that we use on secret key for all channels.
```yaml
channels:
  secret_channel: hlf--channels
  channel_list:
    foochannel:
      msps:
        - BetaMSP
      channel_name: foochannel
      channel_profile: "FooChannel"
    barchannel:
      msps:
        - BetaMSP
      channel_name: barchannel
      channel_profile: "BarChannel"
```
Then modify the `create_secret_from_file` such that it will put multiple files inside a secret. 

Please put your suggestions on which way to go?
